title: omer faruk zorlu
email: omer@zor.lu
title: Hi, I am omer zorlu
description: "Software Developer"
baseurl: ""
url: "https://blog.zor.lu"
twitter_username: omerfarukz
github_username:  omerfarukz
author:
  name: Omer Faruk Zorlu
  email: "omer@zor.lu"

google_analytics: "G-FD461DPJH3"
show_excerpts: true

remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%b %-d, %Y"
  social_links:
    twitter: omerfarukz
    github: omerfarukz
    stackoverflow: "2137094"
    linkedin: omerfarukz



plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/

