title: omer faruk zorlu
email: omer@zor.lu
description: "Software Developer"
baseurl: ""
url: "https://blog.zor.lu"
twitter_username: omerfarukz
github_username:  omerfarukz

theme: minima
plugins:
  - jekyll-feed

exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/

