title: Hi, I am omer@zor.lu
description: "Software Developer"
author:
  name: Omer Faruk Zorlu
  email: "omer@zor.lu"

theme: minima
minima:
  skin: auto
  date_format: "%b %-d, %Y"
  social_links:
    twitter: omerfarukz
    github: omerfarukz
    stackoverflow: "2137094"
    linkedin: omerfarukz

plugins:
  - jekyll-feed

exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/

