title: Hi, I am omer@zor.lu
description: "Software Developer"
name: Omer Faruk Zorlu
email: "omer@zor.lu"

twitter_username: omerfarukz
github_username:  omerfarukz
linkedin_username: omerfarukz
rss: rss

show_excerpts: true

remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%b %-d, %Y"
  social_links:
    twitter: omerfarukz
    github: omerfarukz
    stackoverflow: "2137094"
    linkedin: omerfarukz


plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/

