title: omer faruk zorlu
email: omer@zor.lu
description: "Developer"
baseurl: ""
url: "https://blog.zor.lu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: omerfarukz
github_username:  omerfarukz

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/

